# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     kompose.cmd: C:\Users\hermann90\projects\final_full\test_kompose\kompose.exe convert
#     kompose.version: 1.26.0 (40646f47)
#   labels:
#     io.kompose.service: fastfoodbackend
#   name: sfastfoodbackend
# spec:
#   ports:
#     - name: "8094"
#       port: 8094
#       targetPort: 8094
#   selector:
#     io.kompose.service: fastfoodbackend
# status:
#   loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-cip-service
spec:
  selector:
    app: hello
    tier: backend
  ports:
    - protocol: TCP
      port: 8094
      targetPort: 8094
...