apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\hermann90\projects\final_full\test_kompose\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: fastfoodbackend
  name: fastfoodbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fastfoodbackend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\hermann90\projects\final_full\test_kompose\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/back-tier: "true"
        io.kompose.network/db-tier: "true"
        io.kompose.service: fastfoodbackend
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: userauth
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_PASSWORD
              value: lWZRv2D2SEX32Y5RgdC5J
            - name: MYSQL_USER
              value: admin
          image: hermann90/fastfood_backend:latest
          name: fastfoodbackend
          ports:
            - containerPort: 8094
          resources: {}
      restartPolicy: Always
status: {}
